<a href="https://colab.research.google.com/github/divyanshpandey26/bengaluru-house-price-predictor/blob/main/Bengaluru_House_Price_CODE_divyansh.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

df = pd.read_csv("/content/bengaluru_house_prices.csv")

df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [4]:
df = df.drop(['area_type'], axis=1)
df.head()

,availability,location,size,society,total_sqft,bath,balcony,price
0,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [5]:
df = df.drop(['availability'], axis=1)
df.head()

,location,size,society,total_sqft,bath,balcony,price
0,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [6]:
df=df.drop(['society'],axis=1)
df.head()

                   location       size total_sqft  bath  balcony   price
0  Electronic City Phase II      2 BHK       1056   2.0      1.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0      3.0  120.00
2               Uttarahalli      3 BHK       1440   2.0      3.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0      1.0   95.00
4                  Kothanur      2 BHK       1200   2.0      1.0   51.00

In [7]:
df=df.drop(['balcony'],axis=1)
df.head()

                   location       size total_sqft  bath   price
0  Electronic City Phase II      2 BHK       1056   2.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2               Uttarahalli      3 BHK       1440   2.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                  Kothanur      2 BHK       1200   2.0   51.00

In [8]:
df['bhk'] = df['size'].astype(str).apply(lambda x: int(x.split()[0]) if isinstance(x, str) and x.split()[0].isdigit() else None)

df = df.dropna(subset=['bhk'])

df.head()

                   location       size total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK       1056   2.0   39.07  2.0
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00  4.0
2               Uttarahalli      3 BHK       1440   2.0   62.00  3.0
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00  3.0
4                  Kothanur      2 BHK       1200   2.0   51.00  2.0

In [9]:
df=df.drop(['size'],axis=1)
df.head()

                   location total_sqft  bath   price  bhk
0  Electronic City Phase II       1056   2.0   39.07  2.0
1          Chikka Tirupathi       2600   5.0  120.00  4.0
2               Uttarahalli       1440   2.0   62.00  3.0
3        Lingadheeranahalli       1521   3.0   95.00  3.0
4                  Kothanur       1200   2.0   51.00  2.0

In [10]:
def convert_sqft(x):
    try:
        if '-' in str(x):
            a, b = x.split('-')
            return (float(a) + float(b)) / 2
        return float(x)
    except:
        return None

df['total_sqft'] = df['total_sqft'].apply(convert_sqft)

df = df.dropna(subset=['total_sqft'])

df.head()

                   location  total_sqft  bath   price  bhk
0  Electronic City Phase II      1056.0   2.0   39.07  2.0
1          Chikka Tirupathi      2600.0   5.0  120.00  4.0
2               Uttarahalli      1440.0   2.0   62.00  3.0
3        Lingadheeranahalli      1521.0   3.0   95.00  3.0
4                  Kothanur      1200.0   2.0   51.00  2.0

In [11]:
clean_path = "/content/cleaned_bengaluru.csv"
df.to_csv(clean_path, index=False)

print("✅ Cleaned dataset saved successfully at:", clean_path)

df.head()

✅ Cleaned dataset saved successfully at: /content/cleaned_bengaluru.csv

                   location  total_sqft  bath   price  bhk
0  Electronic City Phase II      1056.0   2.0   39.07  2.0
1          Chikka Tirupathi      2600.0   5.0  120.00  4.0
2               Uttarahalli      1440.0   2.0   62.00  3.0
3        Lingadheeranahalli      1521.0   3.0   95.00  3.0
4                  Kothanur      1200.0   2.0   51.00  2.0

In [12]:

import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error
import joblib
import warnings
warnings.filterwarnings("ignore")

DATA_PATH = "/content/cleaned_bengaluru.csv"
if not os.path.exists(DATA_PATH):
    raise FileNotFoundError(f"Cleaned file not found at {DATA_PATH}. Upload it to Colab or change the path.")

df = pd.read_csv(DATA_PATH)
print("Loaded dataset rows:", len(df))
print(df.head())

FEATURES = ['location', 'bhk', 'total_sqft', 'bath']
TARGET = 'price'

df = df.dropna(subset=FEATURES + [TARGET]).reset_index(drop=True)

X = df[FEATURES].copy()
y = df[TARGET].copy()

X['bhk'] = pd.to_numeric(X['bhk'], errors='coerce')
X['total_sqft'] = pd.to_numeric(X['total_sqft'], errors='coerce')
X['bath'] = pd.to_numeric(X['bath'], errors='coerce')

good = X.notnull().all(axis=1)
X = X[good].reset_index(drop=True)
y = y[good].reset_index(drop=True)

print("\nFeature stats:")
print(X.describe())

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42
)
print("\nTrain rows:", len(X_train), "Test rows:", len(X_test))

categorical_features = ['location']
numeric_features = ['bhk', 'total_sqft', 'bath']

try:
    enc = OneHotEncoder(handle_unknown='ignore', sparse=False)
except TypeError:
    enc = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

preprocessor = ColumnTransformer(transformers=[
    ('cat', enc, categorical_features),
    ('num', StandardScaler(), numeric_features)
])

model = Pipeline(steps=[
    ('pre', preprocessor),
    ('reg', LinearRegression())
])

print("\nTraining model...")
model.fit(X_train, y_train)
print("Model trained.")

y_pred = model.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f"\nTest RMSE: {rmse:.4f}  (units same as 'price' column)")

comp = pd.DataFrame({
    'location': X_test['location'].values,
    'bhk': X_test['bhk'].values,
    'total_sqft': X_test['total_sqft'].values,
    'bath': X_test['bath'].values,
    'actual_price': y_test.values,
    'pred_price': np.round(y_pred, 3)
})
print("\nSample predictions:")
print(comp.head(8))

OUT_MODEL = "/content/bengaluru_price_model.joblib"
joblib.dump(model, OUT_MODEL)
print(f"\nSaved pipeline to: {OUT_MODEL}")

def ask_and_predict(pipeline):
    """Interactive loop to input features and get predicted price."""
    print("\n--- Interactive prediction ---")
    print("Type 'exit' to stop.")
    while True:
        s = input("Enter BHK (e.g. 2) or 'exit': ").strip()
        if s.lower() == 'exit':
            break
        try:
            bhk = float(s)
        except:
            print("Invalid bhk. Try again.")
            continue

        loc = input("Enter location (exact or new name): ").strip()
        sqft_s = input("Enter total_sqft (e.g. 1200): ").strip()
        bath_s = input("Enter bath (e.g. 2): ").strip()
        try:
            sqft = float(sqft_s)
            bath = float(bath_s)
        except:
            print("Invalid numeric input for sqft or bath. Try again.")
            continue

        sample = pd.DataFrame([{
            'location': loc,
            'bhk': bhk,
            'total_sqft': sqft,
            'bath': bath
        }])
        pred = pipeline.predict(sample)[0]
        print(f"Predicted price: {pred:.3f} (same units as dataset)\n")

print("\nTo try interactive prediction, call: ask_and_predict(model)")

Loaded dataset rows: 13258
                   location  total_sqft  bath   price  bhk
0  Electronic City Phase II      1056.0   2.0   39.07  2.0
1          Chikka Tirupathi      2600.0   5.0  120.00  4.0
2               Uttarahalli      1440.0   2.0   62.00  3.0
3        Lingadheeranahalli      1521.0   3.0   95.00  3.0
4                  Kothanur      1200.0   2.0   51.00  2.0

Feature stats:
                bhk    total_sqft          bath
count  13200.000000  13200.000000  13200.000000
mean       2.800833   1555.302783      2.691136
std        1.292843   1237.323445      1.338915
min        1.000000      1.000000      1.000000
25%        2.000000   1100.000000      2.000000
50%        3.000000   1275.000000      2.000000
75%        3.000000   1672.000000      3.000000
max       43.000000  52272.000000     40.000000

Train rows: 10560 Test rows: 2640

Training model...
Model trained.

Test RMSE: 86.3599  (units same as 'price' column)

Sample predictions:
             location  bhk  total_sqft  bath  actual_price  pred_price
0              Jakkur  2.0      1290.0   2.0          80.0      81.724
1     Ullal Uppanagar  6.0      2400.0   5.0          75.0     238.376
2            KR Puram  3.0      1430.0   2.0          61.0      55.661
3         Devanahalli  3.0      1290.0   2.0          62.0      85.679
4            Budigere  2.0      1153.0   2.0          56.5      47.727
5     Electronic City  1.0       550.0   1.0          27.0      22.311
6        Varthur Road  3.0      1247.0   2.0          58.0      55.294
7  8th Phase JP Nagar  2.0      1513.0   2.0          62.0      65.522

Saved pipeline to: /content/bengaluru_price_model.joblib

To try interactive prediction, call: ask_and_predict(model)

In [13]:
import pandas as pd
import joblib

model = joblib.load("/content/bengaluru_price_model.joblib")

print("🏠 Bengaluru House Price Predictor 🧮")
print("====================================")

location = input("Enter location (e.g. Whitefield): ")
bhk = float(input("Enter number of bedrooms (BHK): "))
sqft = float(input("Enter total square feet area: "))
bath = float(input("Enter number of bathrooms: "))

data = pd.DataFrame([{
    'location': location,
    'bhk': bhk,
    'total_sqft': sqft,
    'bath': bath
}])

pred_price = model.predict(data)[0]

print("\n====================================")
print(f"Predicted Price for this house: ₹{pred_price:.2f} lakhs")
print("====================================")

🏠 Bengaluru House Price Predictor 🧮
====================================
Enter location (e.g. Whitefield): whitefield
Enter number of bedrooms (BHK): 3
Enter total square feet area: 1200
Enter number of bathrooms: 1

====================================
Predicted Price for this house: ₹53.60 lakhs
====================================

In [14]:
known_locations = model.named_steps['pre'].transformers_[0][1].categories_[0]

print(f"Total trained locations: {len(known_locations)}\n")
print("Sample locations:")
print(known_locations[:50])

Total trained locations: 1188

Sample locations:
[' Banaswadi' ' Basavangudi' ' Bhoganhalli' ' Devarabeesana Halli'
 ' Devarachikkanahalli' ' Mysore Highway' ' Rachenahalli' ' Thanisandra'
 ' Whitefield' ' south' '1 Annasandrapalya' '1 Giri Nagar' '1 Immadihalli'
 '1A Block Koramangala' '1Channasandra' '1Hanuman Nagar' '1Kasavanhalli'
 '1st Block BEL Layout' '1st Block HBR Layout' '1st Block HRBR Layout'
 '1st Block Jayanagar' '1st Block Koramangala' '1st Phase JP Nagar'
 '1st Stage Domlur' '1st Stage Indira Nagar' '2nd Block Bel Layout'
 '2nd Block Hrbr Layout' '2nd Block Jayanagar' '2nd Block Koramangala'
 '2nd Phase JP Nagar' '2nd Phase Judicial Layout'
 '2nd Stage Arekere Mico Layout' '2nd Stage Nagarbhavi'
 '2nd phase jp nagar, jp nagar' '3rd Block Banashankari'
 '3rd Block Hrbr Layout' '3rd Block Jayanagar' '3rd Block Koramangala'
 '3rd Phase Iti Layout' '3rd Phase JP Nagar'
 '4 Bedroom Farm House in Bagalur' '4th Block HBR Layout'
 '4th Block Jayanagar' '4th Block Koramangala' '4th Phase JP Nagar'
 '4th T block Jayanagar' '5th Block Hbr Layout' '5th Block Jayanagar'
 '5th Phase JP Nagar' '5th Stage BEML Layout']